apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asus-web
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "kuard.asus.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80
