kind: Namespace
apiVersion: v1
metadata:
  name: rr
  labels:
    name: rr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rr
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
---
apiVersion: v1
kind: Service
metadata:
  namespace: rr
  name: mongo
spec:
  type: LoadBalancer
  ports:
  - name: mongodb
    targetPort: 27017
    port: 80
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rr
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
---
apiVersion: v1
kind: Service
metadata:
  namespace: rr
  name: redis
spec:
  type: LoadBalancer
  ports:
  - name: redis
    targetPort: 6379
    port: 80
  selector:
    app: redis
